historical_data_view:
  auto_hide_empty_columns: true
  hide_all_zero_columns: true
  hide_all_one_columns: true
  column_groups:
    price_data:
      - name: Date
        field: date
        simple_view: true
      - name: Close
        field: close_price
        simple_view: true
      - name: Open Price
        field: open_price
        simple_view: false
      - name: High Price
        field: high_price
        simple_view: false
      - name: Low Price
        field: low_price
        simple_view: false
      - name: Volume
        field: volume
        simple_view: false
    transaction_data:
      - name: Type
        field: transaction_type
        simple_view: true
      - name: Adjusted Quantity
        field: adjusted_quantity
        simple_view: false
      - name: Adjusted Price
        field: adjusted_price
        simple_view: true
      - name: Net Quantity
        field: net_transaction_quantity
        simple_view: false
    position_metrics:
      - name: Total Shares
        field: total_shares_owned
        simple_view: true
      - name: Total Investment
        field: total_investment_amount
        simple_view: false
      - name: Current Cost Basis
        field: current_cost_basis
        simple_view: true
      - name: Cost Basis Variation
        field: cost_basis_variation
        simple_view: false
      - name: Cumulative Cost Basis Variation
        field: cumulative_cost_basis_variation
        simple_view: false
    performance_metrics:
      - name: Market Value
        field: market_value
        simple_view: true
      - name: Daily P/L
        field: daily_pl
        simple_view: false
      - name: Daily P/L %
        field: daily_pl_pct
        simple_view: false
      - name: Realised P/L
        field: realised_pl
        simple_view: true
      - name: Unrealised P/L
        field: unrealised_pl
        simple_view: true
      - name: Total Return $
        field: total_return
        simple_view: true
      - name: Total Return %
        field: total_return_pct
        simple_view: true
      - name: Cumulative Return %
        field: cumulative_return_pct
        simple_view: true
    dividend_data:
      - name: Dividend
        field: dividend
        simple_view: true
      - name: Cash Dividend
        field: cash_dividend
        simple_view: false
      - name: Total Cash Dividends
        field: cash_dividends_total
        simple_view: false
      - name: DRP Shares
        field: drp_share
        simple_view: false
      - name: Total DRP Shares
        field: drp_shares_total
        simple_view: false
    corporate_actions:
      - name: DRP Flag
        field: drp_flag
        simple_view: true
      - name: Split Ratio
        field: split_ratio
        simple_view: true
      - name: Cumulative Split Ratio
        field: cumulative_split_ratio
        simple_view: true
  column_formats:
    price_formats:
      default: .2f
      custom: {}
    percentage_formats:
      default: .2f
      custom: {}
    quantity_formats:
      default: .4f
      custom: {}
  profit_loss_calculations:
    default_method: fifo
    available_methods:
    - fifo
    - lifo
    - hifo
portfolio_study_view:
  hierarchy:
    market_value:
      name: Market Value
      view_types:
        individual_stocks:
          name: Individual Stocks
          chart_types:
            line_chart:
              name: Line Chart
        portfolio_total:
          name: Portfolio Total
          chart_types:
            line_chart:
              name: Line Chart
            stacked_area:
              name: Stacked Area
    profitability:
      name: Profitability
      view_types:
        individual_stocks:
          name: Individual Stocks
          chart_types:
            dollar_value:
              name: Total Return $
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            percentage:
              name: Total Return %
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            aggregated_percentage:
              name: Aggregated ROI %
              time_periods:
                cumulative: Cumulative
        portfolio_total:
          name: Portfolio Total
          chart_types:
            dollar_value:
              name: Total Return $
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            percentage:
              name: Total Return %
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
    dividend_performance:
      name: Dividend Performance
      view_types:
        individual_stocks:
          name: Individual Stocks
          chart_types:
            cash:
              name: Cash Dividends
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            drp:
              name: DRP
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            combined:
              name: Cash + DRP
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
        portfolio_total:
          name: Portfolio Total
          chart_types:
            cash:
              name: Cash Dividends
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            drp:
              name: DRP
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
            combined:
              name: Cash + DRP
              time_periods:
                daily: Daily Changes
                cumulative: Cumulative
    portfolio_distribution:
      name: Portfolio Distribution
